# Full reference https://github.com/foundry-rs/foundry/tree/master/crates/config

[profile.default]
  allow_paths = ["node_modules", "../../node_modules/",]
  auto_detect_solc = false
  block_timestamp = 1_680_220_800 # March 31, 2023 at 00:00 GMT
  bytecode_hash = "none"
  evm_version = "shanghai"
  ffi = true
  fuzz = { runs = 1_00 }
  max_gas = 9_223_372_036_854_775_807
  optimizer = true
  optimizer_runs = 10_000
  out = "out"
  script = "script"
  solc = "0.8.28"
  src = "src"
  test = "test"
  
  # Add post-build hook
  extra_output = ["abi", "metadata"]
  build_info = true

[profile.prod]
  via_ir = true
  optimizer = true
  optimizer_runs = 100_000

[profile.ci]
  fuzz = { runs = 10_000 }
  verbosity = 4

[etherscan]
  local = { key = "${ETHERSCAN_API_KEY}" }
  base = { key = "${ETHERSCAN_API_KEY}" }
  base_sepolia = { key = "${ETHERSCAN_API_KEY}" }

[fmt]
  bracket_spacing = true
  int_types = "long"
  line_length = 120
  multiline_func_header = "all"
  number_underscore = "thousands"
  quote_style = "double"
  tab_width = 4
  wrap_comments = true

[rpc_endpoints]
  local = "http://localhost:8545"
  base = "https://base-mainnet.g.alchemy.com/v2/${ALCHEMY_API_KEY}"
  base_sepolia = "https://base-sepolia.g.alchemy.com/v2/${ALCHEMY_API_KEY}"
